version: 2
registries:
  npm-registry-node-bit-dev:
    type: npm-registry
    url: https://node.bit.dev
    token: "${{secrets.NPM_REGISTRY_NODE_BIT_DEV_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "00:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  ignore:
  - dependency-name: gulp-shell
    versions:
    - "> 0.7.1"
  - dependency-name: "@angular/cli"
    versions:
    - 11.1.2
    - 11.1.4
    - 11.2.0
    - 11.2.1
    - 11.2.10
    - 11.2.2
    - 11.2.3
    - 11.2.4
    - 11.2.5
    - 11.2.6
    - 11.2.7
    - 11.2.8
    - 11.2.9
  - dependency-name: "@angular-devkit/architect"
    versions:
    - 0.1101.2
    - 0.1101.4
    - 0.1102.0
    - 0.1102.1
    - 0.1102.10
    - 0.1102.2
    - 0.1102.3
    - 0.1102.4
    - 0.1102.5
    - 0.1102.6
    - 0.1102.7
    - 0.1102.8
    - 0.1102.9
  - dependency-name: "@angular/language-service"
    versions:
    - 11.1.1
    - 11.1.2
    - 11.2.0
    - 11.2.1
    - 11.2.10
    - 11.2.11
    - 11.2.2
    - 11.2.3
    - 11.2.4
    - 11.2.5
    - 11.2.6
    - 11.2.7
    - 11.2.9
  - dependency-name: firebase-tools
    versions:
    - 9.2.2
    - 9.3.0
    - 9.4.0
    - 9.5.0
    - 9.6.0
    - 9.6.1
    - 9.7.0
    - 9.8.0
    - 9.9.0
  - dependency-name: bl
    versions:
    - 4.0.4
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  registries:
  - npm-registry-node-bit-dev
- package-ecosystem: docker
  directory: "/.devcontainer"
  schedule:
    interval: weekly
    time: "00:00"
  open-pull-requests-limit: 10
