image: node:11

stages:
  - install
  - build
  - deploy

install-dependencies:
  stage: install
  cache:
    policy: push
    paths:
      - node_modules/
  script:
    - npm install
  only:
    changes:
      - package.json

build:
  stage: build
  cache:
    policy: pull
    paths:
      - node_modules/
  script:
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist/

ggtavern:
  stage: deploy
  cache:
    policy: pull
    paths:
      - node_modules/
  only: 
    - develop
    - release
    - hotfix
    - master
  script: npm run deploy
  environment:
    name: production
    url: https://ggtavern.admiralfeb.net
  dependencies:
    - build