image: registry.gitlab.com/admiralfeb/ggtavern.pub:latest

stages:
  - install
  - test
  - build
  - deploy

install-dependencies:
  stage: install
  cache:
    policy: push
    paths:
      - node_modules/
  script:
    - npm install
  only:
    changes:
      - package.json

lint:
  stage: test
  cache:
    policy: pull
    paths:
      - node_modules/
  allow_failure: true
  script:
    - npm run lint

unit_test:
  stage: test
  cache:
    policy: pull
    paths:
      - node_modules/
  script:
    - npm run test-ci

e2e_test:
  stage: test
  cache:
    policy: pull
    paths:
      - node_modules/
  script:
    - npm run e2e-ci

build:
  stage: build
  cache:
    policy: pull
    paths:
      - node_modules/
  script:
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist/

ggtavern:
  stage: deploy
  cache:
    paths:
      - node_modules/
      - .firebase/
  only: 
    - develop
    - release
    - hotfix
    - master
  script: npm run deploy
  environment:
    name: production
    url: https://ggtavern.admiralfeb.net
  dependencies:
    - build