# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

variables:
  NPM_CACHE_FOLDER: $(Pipeline.Workspace)/.npm

stages:
- stage: build
  jobs:
  - job:
    displayName: Install, Build, Test
    pool: Default
    #container: admiralfeb/dev:angular
    steps:
    - task: Npm@1
      displayName: Install
      inputs:
        command: 'install'
    - task: Npm@1
      displayName: Test
      inputs:
        command: 'custom'
        customCommand: 'run test-ci'
    - task: Npm@1
      displayName: e2e
      inputs:
        command: 'custom'
        customCommand: 'run e2e-ci'
    - task: Npm@1
      displayName: Build
      inputs:
        command: 'custom'
        customCommand: 'run build'

