# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

variables:
  NPM_CACHE_FOLDER: $(Pipeline.Workspace)/.npm


stages:
- stage: Install
  jobs:
  - job:
    displayName: Install
    pool: Default
    #container: admiralfeb/dev:angular
    steps:
    - task: Npm@1
      displayName: Install
      inputs:
        command: 'install'
    - task: PublishPipelineArtifact@1
      displayName: Save node_modules
      inputs:
        targetPath: 'node_modules'
        artifact: 'node_modules'
- stage: Test
  jobs:
  - job:
    displayName: Unit Test
    pool: Default
    #container: admiralfeb/dev:angular
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        targetPath: '$(Pipeline.Workspace)'
    - task: Npm@1
      displayName: Test
      inputs:
        command: 'custom'
        customCommand: 'run test-ci'
  - job:
    displayName: e2e Test
    pool: Default
    #container: admiralfeb/dev:angular
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        targetPath: '$(Pipeline.Workspace)'
    - task: Npm@1
      displayName: e2e
      inputs:
        command: 'custom'
        customCommand: 'run e2e-ci'
- stage: Build
  jobs:
  - job:
    displayName: Build
    pool: Default
    #container: admiralfeb/dev:angular
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        targetPath: '$(Pipeline.Workspace)'
    - task: Npm@1
      displayName: Build
      inputs:
        command: 'custom'
        customCommand: 'run build'
    - task: CopyFiles@2
      displayName: Copy build files to stage
      inputs:
        SourceFolder: 'dist'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/dist'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'dist'
        publishLocation: 'Container'
- stage: Deploy
  jobs:
    - deployment:
      displayName: Deploy to Firebase
      pool: Default
      environment: ggtavern-admiralfeb
      strategy:
        runOnce:
          deploy:
            steps:
            - task: DownloadPipelineArtifact@2
              inputs:
                artifactName: 'dist'
                buildType: 'current'
                targetPath: '$(Pipeline.Workspace)'
            - task: Npm@1
              inputs:
                command: 'custom'
                customCommand: 'run deploy'
              env:
                FIREBASE_TOKEN: $(FIREBASE_TOKEN)

